# Generated by Django 5.1.6 on 2025-10-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True, verbose_name="文字答案")),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否正確"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作答時間"),
                ),
            ],
            options={
                "verbose_name": "作答記錄",
                "verbose_name_plural": "作答記錄",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="選課時間"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="課程",
                    ),
                ),
            ],
            options={
                "verbose_name": "選課記錄",
                "verbose_name_plural": "選課記錄",
            },
        ),
    ]
