# Generated by Django 5.1.6 on 2025-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="核准時間"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待審核"),
                    ("approved", "已核准"),
                    ("rejected", "已拒絕"),
                ],
                default="pending",
                max_length=20,
                verbose_name="審核狀態",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="申請時間"),
        ),
    ]
