# Generated by Django 5.1.6 on 2025-11-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_enrollment_approved_at_enrollment_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together=set(),
        ),
    ]
