# Generated by Django 5.1.6 on 2025-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("A", "A 組"), ("B", "B 組"), ("C", "C 組")],
                max_length=1,
                null=True,
                verbose_name="學生等級",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="placement_test_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="完成預先測驗時間"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="placement_test_score",
            field=models.FloatField(blank=True, null=True, verbose_name="預先測驗成績"),
        ),
    ]
