# Generated by Django 5.2.8 on 2025-11-17 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_is_default_placement"),
        ("users", "0002_user_level_user_placement_test_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.grade",
                verbose_name="年級",
            ),
        ),
    ]
