# Generated by Django 5.2.8 on 2025-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("advanced", "進階級"),
                    ("standard", "標準級"),
                    ("basic", "基礎級"),
                ],
                max_length=20,
                null=True,
                verbose_name="學生等級",
            ),
        ),
    ]
