# Generated by Django 5.1.6 on 2025-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="選項內容")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正確"),
                ),
                ("order", models.IntegerField(verbose_name="順序")),
            ],
            options={
                "verbose_name": "選項",
                "verbose_name_plural": "選項",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="題目內容")),
                ("explanation", models.TextField(blank=True, verbose_name="詳解")),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "簡單"), (2, "中等"), (3, "困難")],
                        default=2,
                        verbose_name="難度",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="題目順序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "題目",
                "verbose_name_plural": "題目",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="類型名稱")),
            ],
            options={
                "verbose_name": "題目類型",
                "verbose_name_plural": "題目類型",
            },
        ),
    ]
