# Generated by Django 5.1.6 on 2025-10-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.chapter",
                verbose_name="所屬章節",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="assessments.question",
                verbose_name="所屬題目",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.questiontype",
                verbose_name="題目類型",
            ),
        ),
    ]
