# Generated by Django 5.1.6 on 2025-11-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_count",
            field=models.IntegerField(default=0, verbose_name="正確作答人數"),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_rate",
            field=models.FloatField(default=0.0, verbose_name="正確率 (%)"),
        ),
        migrations.AddField(
            model_name="question",
            name="last_stat_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="最後統計更新時間"),
        ),
        migrations.AddField(
            model_name="question",
            name="total_attempts",
            field=models.IntegerField(default=0, verbose_name="總作答次數"),
        ),
    ]
