# Generated by Django 5.1.6 on 2025-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="章節標題")),
            ],
            options={
                "verbose_name": "章節",
                "verbose_name_plural": "章節",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="課程標題")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="課程描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "課程",
                "verbose_name_plural": "課程",
                "ordering": ["grade", "subject"],
            },
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="學制名稱")),
                ("order", models.IntegerField(verbose_name="排序")),
            ],
            options={
                "verbose_name": "學制",
                "verbose_name_plural": "學制",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="年級名稱")),
                ("order", models.IntegerField(verbose_name="排序")),
            ],
            options={
                "verbose_name": "年級",
                "verbose_name_plural": "年級",
                "ordering": ["education_level__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="科目名稱")),
            ],
            options={
                "verbose_name": "科目",
                "verbose_name_plural": "科目",
            },
        ),
    ]
