# Generated by Django 5.1.6 on 2025-10-23 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="授課教師",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.course",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="education_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.educationlevel",
                verbose_name="所屬學制",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.grade",
                verbose_name="年級",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.subject",
                verbose_name="科目",
            ),
        ),
    ]
