# Generated by Django 5.1.6 on 2025-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="chapter_type",
            field=models.CharField(
                choices=[("regular", "一般章節"), ("placement_test", "預先測驗")],
                default="regular",
                max_length=20,
                verbose_name="章節類型",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("regular", "一般課程"), ("placement_test", "預先測驗")],
                default="regular",
                max_length=20,
                verbose_name="課程類型",
            ),
        ),
    ]
