# Generated by Django 5.1.6 on 2025-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_chapter_chapter_type_course_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_default_placement",
            field=models.BooleanField(default=False, verbose_name="是否為預設預先測驗"),
        ),
    ]
